### ISSUE TITLE
fix fxa-rp key generation

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-dev#106]
Sometimes (maybe always) this keypair is not being generated (or not in the right place). 

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/data/fxa-rp/secret-key.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.KeyPair (/data/fxa-rp/node_modules/

**Comment by jrgm** [comment]
This was fixed by https://github.com/mozilla/fxa-dev/pull/108. Closing
