### ISSUE TITLE
[auth] openid.key is missing; bailing out in a cowardly fashion

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-dev#489]
On starting auth server:

{ AssertionError [ERR_ASSERTION]: openid.key is missing; bailing out in a cowardly fashion...
    at Object.<anonymous> (/app/fxa-oauth-server/lib/keys.js:92:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by vladikoff** [comment]
cc @dannycoates

**Comment by jrgm** [comment]
Maybe needs to be FXA_OPENID_KEYFILE, not FXA_OPENID_KEY in the envionment.
